# Generated by Django 4.2 on 2023-04-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
