# Generated by Django 4.2 on 2023-05-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location_id',
            new_name='location',
        ),
    ]
