# Generated by Django 4.2 on 2023-05-05 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_rename_location_id_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Участник'), ('moderator', 'Модератор'), ('admin', 'Админ')], default='member', max_length=10),
        ),
    ]
