# Generated by Django 4.2 on 2023-05-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
