version: '3.9'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hw_27
      POSTGRES_PASSWORD: hw_27
      POSTGRES_DB: hw_27
    restart: always
    ports:
    - "5433:5432"

volumes:
  postgres_data: